# Run the ssh integration tests in various Docker containers.
# These tests can also be run locally via `make sshintegrationtest`.
name: "ssh-integrationtest"

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

on:
  pull_request:
    paths:
      - "ssh/**"
      - "tempfork/gliderlabs/ssh/**"
      - ".github/workflows/ssh-integrationtest.yml"
jobs:
  ssh-integrationtest:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        include:
          - base: "ubuntu:focal"
            tag: "ssh-ubuntu-focal"
          - base: "ubuntu:jammy"
            tag: "ssh-ubuntu-jammy"
          - base: "ubuntu:noble"
            tag: "ssh-ubuntu-noble"
          - base: "alpine:latest"
            tag: "ssh-alpine-latest"
    steps:
      - name: Check out code
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      - name: Build test binaries
        run: |
          GOOS=linux GOARCH=amd64 CGO_ENABLED=0 ./tool/go test -tags integrationtest -c ./ssh/tailssh -o ssh/tailssh/testcontainers/tailssh.test
          GOOS=linux GOARCH=amd64 CGO_ENABLED=0 ./tool/go build -o ssh/tailssh/testcontainers/tailscaled ./cmd/tailscaled
      - name: Run SSH integration tests (${{ matrix.base }})
        run: |
          docker build --build-arg="BASE=${{ matrix.base }}" -t "${{ matrix.tag }}" ssh/tailssh/testcontainers

  macos-ssh-integrationtest:
    runs-on: macos-latest
    steps:
      - name: Check out code
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      - name: Create test user
        run: |
          set -euxo pipefail

          sudo dscl . -create /Groups/groupone
          sudo dscl . -create /Groups/groupone PrimaryGroupID 10000
          sudo dscl . -create /Groups/groupone Password '*'

          sudo dscl . -create /Groups/grouptwo
          sudo dscl . -create /Groups/grouptwo PrimaryGroupID 10001
          sudo dscl . -create /Groups/grouptwo Password '*'

          sudo dscl . -create /Users/testuser
          sudo dscl . -create /Users/testuser UserShell /bin/bash
          sudo dscl . -create /Users/testuser RealName 'Test User'
          sudo dscl . -create /Users/testuser UniqueID 10002
          sudo dscl . -create /Users/testuser PrimaryGroupID 10000
          sudo dscl . -create /Users/testuser NFSHomeDirectory /Users/testuser

          sudo mkdir -p /Users/testuser
          sudo chown -R testuser:groupone /Users/testuser
          sudo chmod 0755 /Users/testuser

          sudo dseditgroup -o edit -a testuser -t user groupone
          sudo dseditgroup -o edit -a testuser -t user grouptwo
          id testuser
      - name: Build test binaries
        run: |
          ./tool/go test -tags integrationtest -c ./ssh/tailssh -o /tmp/tailssh.test
          ./tool/go build -o /tmp/tailscaled ./cmd/tailscaled
      - name: Run macOS SSH integration tests
        run: |
          sudo env "PATH=$PATH" TAILSCALED_PATH=/tmp/tailscaled /tmp/tailssh.test -test.v -test.timeout=2m -test.run '^(TestOpenSSHExitCodes|TestIntegrationExitCodes)$'
